---
slug: book
filename: book
title: Title of the Book
subtitle: Change me
description: Change me.
author: Author Name
copyright: 2015
uuid: 9233f7b5-4e19-4a84-b9e5-901629aadcc7
pdf_preview_page_range: 1..30
epub_mobi_preview_chapter_range: 0..1
